# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-a704f1f4-b94f-4afe-976e-82e754f0a778";
    fsType = "btrfs";
  };

  boot.initrd.luks.devices."luks-a704f1f4-b94f-4afe-976e-82e754f0a778".device = "/dev/disk/by-uuid/a704f1f4-b94f-4afe-976e-82e754f0a778";

  fileSystems."/home" = {
    device = "/dev/mapper/luks-a704f1f4-b94f-4afe-976e-82e754f0a778";
    fsType = "btrfs";
    options = ["subvol=home"];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/luks-a704f1f4-b94f-4afe-976e-82e754f0a778";
    fsType = "btrfs";
    options = ["subvol=nix"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E99D-6A0F";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/mapper/luks-db6fa79c-115f-4e8f-86e7-fae68ab2ef71";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
