# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-676832ae-1d58-4570-897f-0175565da880";
    fsType = "btrfs";
  };

  boot.initrd.luks.devices."luks-676832ae-1d58-4570-897f-0175565da880".device = "/dev/disk/by-uuid/676832ae-1d58-4570-897f-0175565da880";

  fileSystems."/nix" = {
    device = "/dev/mapper/luks-676832ae-1d58-4570-897f-0175565da880";
    fsType = "btrfs";
    options = ["subvol=nix"];
  };

  fileSystems."/swap" = {
    device = "/dev/mapper/luks-676832ae-1d58-4570-897f-0175565da880";
    fsType = "btrfs";
    options = ["subvol=swap"];
  };

  fileSystems."/home" = {
    device = "/dev/mapper/luks-676832ae-1d58-4570-897f-0175565da880";
    fsType = "btrfs";
    options = ["subvol=home"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0B9E-7F2E";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
